# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
#
Snack.create(name: 'apple', price: 1.00, metadata: 'apple fruit healthy')
Snack.create(name: 'Arnie Palmer', price: 0.70, metadata: 'arnold palmer arnie palmer drink tea lemonade')
Snack.create(name: 'Austin Crackers', price: 0.30, metadata: 'crackers')
Snack.create(name: 'Beef Jerkey', price: 1.10, metadata: 'Beef Jerkey')
Snack.create(name: 'Bowl Noodle Soup', price: 0.90, metadata: 'bowl noodle soup noodles')
Snack.create(name: 'Capri Sun', price: 0.30, metadata: 'capri sun drink juice')
Snack.create(name: 'Cheese-Its', price: 0.40, metadata: 'cheese cheese-its snack')
Snack.create(name: 'Cheetos', price: 0.30, metadata: 'cheetos cheese snack')
Snack.create(name: 'Chef Boyarde', price: 0.90, metadata: 'chef boyarde pasta')
Snack.create(name: 'Chex mix', price: 0.40, metadata: 'chex mix snack')
Snack.create(name: 'Chips (lays)', price: 0.30, metadata: 'chips lays cheetos fritos doritos snack')
Snack.create(name: 'Clemintines', price: 0.30, metadata: 'clementines fruit healthy')
Snack.create(name: 'Cliff Bar', price: 0.90, metadata: 'cliff bar snack')
Snack.create(name: 'Combos', price: 0.50, metadata: 'combos snack')
Snack.create(name: 'Cookies', price: 0.40, metadata: 'cookies snack')
Snack.create(name: 'Cosmic Brownies', price: 0.40, metadata: 'cosmic brownies snack')
Snack.create(name: 'Creme Pie', price: 0.40, metadata: 'little debbie oatmeal creme pie snack')
Snack.create(name: 'Cupcakes', price: 0.70, metadata: 'cupcakes snack')
Snack.create(name: 'Cutties', price: 0.30, metadata: 'cutties snack')
Snack.create(name: 'Donuts', price: 0.50, metadata: 'donuts snack')
Snack.create(name: 'Easymac Bowl', price: 0.90, metadata: 'easymac ez mac ezmac ez-mac macaroni mac and cheese')
Snack.create(name: 'Energy Shots', price: 2.00, metadata: 'energy shots drink')
Snack.create(name: 'Fruit Cups', price: 0.70, metadata: 'fruit cup snack')
Snack.create(name: 'Fruit Snacks', price: 0.20 , metadata: 'fruit snack')
Snack.create(name: 'Gardettos', price: 0.40, metadata: 'gardettos snack')
Snack.create(name: 'Gogurt', price: 0.30, metadata: 'gogurt yogurt snack')
Snack.create(name: 'Goldfish', price: 0.50, metadata: 'goldfish cheese snack')
Snack.create(name: 'Green Tea', price: 0.10, metadata: 'green tea bag drink')
Snack.create(name: 'Gushers', price: 0.30, metadata: 'gushers candy')
Snack.create(name: 'Hershey\'s', price: 0.70, metadata: 'hershey\'s chocolate candy bar')
Snack.create(name: 'Fruit Juice', price: 0.60, metadata: 'fruit juice drink')
Snack.create(name: 'Kit-kat', price: 0.70, metadata: 'kit-kat chocolate candy bar')
Snack.create(name: 'Kureig Cup', price: 0.60, metadata: 'kureig cup coffee drink')
Snack.create(name: 'Little Debbie', price: 0.40, metadata: 'little debbie snack')
Snack.create(name: 'Little Hugs', price: 0.20, metadata: 'little hugs snack')
Snack.create(name: 'Mandarine Oranges', price: 0.70, metadata: 'mandarine oranges fruit snack healthy')
Snack.create(name: 'Mini Pretzels', price: 0.30, metadata: 'mini pretzels snack')
Snack.create(name: 'M&M\'s', price: 0.70, metadata: 'm&m\'s candy')
Snack.create(name: 'Monster', price: 1.40, metadata: 'monster energy drink')
Snack.create(name: 'Muffin', price: 0.60, metadata: 'muffin snack')
Snack.create(name: 'Nature Valley', price: 0.40, metadata: 'nature valley granola bar snack')
Snack.create(name: 'Now & Later', price: 0.20, metadata: 'now & later now and later candy')
Snack.create(name: 'Nut Rolls', price: 0.60, metadata: 'nut rolls candy')
Snack.create(name: 'Oatmeal', price: 0.30, metadata: 'oatmeal breakfast')
Snack.create(name: 'oreo cookies', price: 0.50, metadata: 'oreos oreo cookies chocolate')
Snack.create(name: 'Peanut Butter Crackers', price: 0.20, metadata: 'peanut butter crackers snack')
Snack.create(name: 'Peanuts', price: 0.30, metadata: 'peanuts snack')
Snack.create(name: 'Perrier', price: 0.60, metadata: 'perrier fizzy water drink')
Snack.create(name: 'Pop', price: 0.40, metadata: 'soda pop coke dr pepper dr. pepper mtn dew mountain dew diet coke')
Snack.create(name: 'Popcorn', price: 0.40, metadata: 'microwave popcorn snack')
Snack.create(name: 'Pop-Tarts', price: 0.50, metadata: 'pop-tart snack')
Snack.create(name: 'Powerade', price: 0.60, metadata: 'powerade drink electrolytes')
Snack.create(name: 'Quaker Granola Bars', price: 0.30, metadata: 'quaker chewy gronala bars snack')
Snack.create(name: 'Ramen', price: 0.40, metadata: 'ramen soup')
Snack.create(name: 'Red Bull', price: 1.30, metadata: 'red bull energy drink')
Snack.create(name: 'Reece\'s PB Cup', price: 0.70, metadata: 'reece\'s peanut butter cup candy')
Snack.create(name: 'Rice Krispy', price: 0.50, metadata: 'rice crispy treat rice cripies treat candy')
Snack.create(name: 'Root Beer', price: 0.50, metadata: 'root beer drink')
Snack.create(name: 'Skittles', price: 0.70, metadata: 'skittles candy')
Snack.create(name: 'Snickers', price: 0.60, metadata: 'snickers candy bar')
Snack.create(name: 'Sour Punch', price: 0.60, metadata: 'sour punch candy')
Snack.create(name: 'Starbucks(cold)', price: 1.20, metadata: 'starbucs frappuccino frap coffee drink')
Snack.create(name: 'Starburst', price: 0.70, metadata: 'starburst candy')
Snack.create(name: 'String Cheese', price: 0.30, metadata: 'string cheese snack')
Snack.create(name: 'Swiss Miss', price: 0.20, metadata: 'swiss miss hot chocolate drink')
Snack.create(name: 'Trail Mix', price: 0.40, metadata: 'trail mix snack')
Snack.create(name: 'Veggie Straws', price: 0.40, metadata: 'veggie straws snack')
Snack.create(name: 'Vicky\'s Kettle Cooked', price: 0.50, metadata: 'vicky\'s chips vicky\'s kettle chips snack')
Snack.create(name: 'Water', price: 0.20, metadata: 'water drink')
Snack.create(name: 'Yogurt', price: 0.50, metadata: 'yogurt snack')
